// This file is auto-generated by openapi-typescript
// Run: bun run generate-api

export interface paths {
  "/api/v1/sync": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            url: string;
            audio_format?: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "text/event-stream": string;
          };
        };
      };
    };
  };
  "/api/v1/sync/blocking": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            url: string;
            audio_format?: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              success: boolean;
              album: {
                title: string;
                artist: string;
                year: number | null;
                track_count: number;
              } | null;
              destination: string | null;
              track_count: number;
              error: string | null;
            };
          };
        };
      };
    };
  };
  "/health": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              status: string;
            };
          };
        };
      };
    };
  };
}

export interface components {}
export interface operations {}
